# from django.core.exceptions import ValidationError


class ProductValidator:
    def __init__(self): ...

    def __call__(self):
        return True


class OrderValidator:
    def __init__(self): ...

    def __call__(self):
        return True


class OrderitemsValidator:
    def __init__(self): ...

    def __call__(self):
        return True


class CartValidator:
    def __init__(self): ...

    def __call__(self):
        return True
